apiVersion: v1
kind: Service
metadata:
  name: dolistservice
spec:
  type: NodePort
  selector:
    app: 2dolist-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: 30001
